name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vsysoev/aflplusplus-cmake:$(date +%s) --tag vsysoev/aflplusplus-cmake:latest
  
  publish:
    runs-on: ubuntu-latest
    needs:
      build
    steps:
    - uses: actions/checkoiut@v2
    - name: Publish the tagged Docker image
      run: docker push vsysoev/aflplusplus-cmake:$(date +%s)
    - name: Publish the latest Docker image 
      run: docker push vsysoev/aflplusplus-cmake:latest
